### ISSUE TITLE
Integration tests failing

### ISSUE THREAD

**Issue by sopgreg** [holodeck-b2b/Holodeck-B2B#121]
Hi, integration tests are failing for me on master branch on Windows. I see the directories being created, also the ``.appected and .mmd files (which get cleaned up after the test)

I there something I can do to fix this?

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Setting up the OneWay integration test ... 
	Unzipping HolodeckB2B instance ... done.
	Unzipping HolodeckB2B instance ... done.
	Configuring HolodeckB2B instances ... done.
	Starting HolodeckB2B instances ... done.
Setting up the OneWay integration test finished.
Running org.holodeckb2b.test.integration.OneWayMEPWorkflows
The OneWay/Pull integration test started ... 
Using JAVA_HOME    C:\Users\scgr\.jdks\azul-1.8.0_302\jre
Using HB2B_HOME    C:\Dev\Holodeck-B2B\modules\holodeckb2b-it\target\test-classes\integ\HolodeckB2B-A\bin\..
Using JAVA_HOME    C:\Users\scgr\.jdks\azul-1.8.0_302\jre
Using HB2B_HOME    C:\Dev\Holodeck-B2B\modules\holodeckb2b-it\target\test-classes\integ\HolodeckB2B-B\bin\..
[HolodeckB2BServer] Starting server
[HolodeckB2BServer] Starting server
Starting Holodeck B2B Core module...
Starting Holodeck B2B Core module...
Message to pull is placed into msg_out dir. Waiting for message processing ... 
Holodeck B2B Core module started.
Holodeck B2B Core module started.
[HolodeckB2BServer] Started server
[HolodeckB2BServer] Started server
Message should be processed now. Checking the results ...
The OneWay/Push integration test started ... 
Message to push is placed into msg_out dir. Waiting for message processing ... 
Message should be processed now. Checking the results ...
Cleaning up the OneWay integration test resources ... done.
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 110.62 sec <<< FAILURE! - in org.holodeckb2b.test.integration.OneWayMEPWorkflows
testOneWayPull(org.holodeckb2b.test.integration.OneWayMEPWorkflows)  Time elapsed: 65.077 sec  <<< FAILURE!
java.lang.AssertionError
	at org.holodeckb2b.test.integration.OneWayMEPWorkflows.testOneWayPull(OneWayMEPWorkflows.java:168)

testOneWayPush(org.holodeckb2b.test.integration.OneWayMEPWorkflows)  Time elapsed: 45.069 sec  <<< FAILURE!
java.lang.AssertionError
	at org.holodeckb2b.test.integration.OneWayMEPWorkflows.testOneWayPush(OneWayMEPWorkflows.java:125)


Results :

Failed tests: 
  OneWayMEPWorkflows.testOneWayPull:168
  OneWayMEPWorkflows.testOneWayPush:125

Tests run: 2, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by RenateS** [comment]
We know that there occasionally is a timing issue with the integration tests. It is on our list for future attention.
