### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by hkreetz** [holodeck-b2b/Holodeck-B2B#131]
Hello!

When we are trying to send a message via AS4, using a x509 cert, a NullPointerException occured.
Without using certs, it works.

**ServerA: VCOMMSTAGE10 (Sender):**

- Holodeck 5.3.2
- Java 1.8.0.333
- Windows 2012R2

- PMode: .\holodeck-b2b-A\repository\pmodes\ex-pm-pull-x509-init.xml

`
	<Protocol>
		<Address>http://VCOMMSTAGE11:9090/holodeckb2b/as4</Address>
	</Protocol>
`

- Certs: .\holodeck-b2b-A\repository\certs\ 

	We've copied over: partnerkeys.jks, privatekeys.jks & trustedcerts.jks, from the example folder)

------------------------------------------------------------------------------------------------------------------------------------------

**ServerB: VCOMMSTAGE11 (Receiver):**

- Holodeck 5.3.2
- Java 1.8.0.333
- Windows 2012R2

- Conf: .\holodeck-b2b-B\conf\holodeckb2b.xml

`
<transportReceiver name="http">
			class="org.holodeckb2b.core.axis2.HTTPListener">
			<parameter name="port">9090</parameter>
</transportReceiver>
`

- PMode: .\holodeck-b2b-B\repository\pmodes\ex-pm-pull-x509-resp.xml

- Certs: .\holodeck-b2b-B\repository\certs\ 

	We've copied over: partnerkeys.jks, privatekeys.jks & trustedcerts.jks, from the example folder)

-----------------------------------------------------------------------------------------------------------------------------------------

* ServerA: Sending ex-mmd-pull-x509.mmd --> ex-mmd-pull-x509.err, ex-mmd-pull-x509.rejected 

ERROR:

The message could not be submitted to Holodeck B2B due to an error:

Error type:    NullPointerException
Error message: null

Error details
-------------
Exception cause: unknown
Stacktrace:
java.lang.NullPointerException
	at org.holodeckb2b.core.submission.MMDCompleter.complete(MMDCompleter.java:107)
	at org.holodeckb2b.core.submission.MMDCompleter.complete(MMDCompleter.java:92)
	at org.holodeckb2b.core.submission.MessageSubmitter.doSubmission(MessageSubmitter.java:106)
	at org.holodeckb2b.core.submission.MessageSubmitter.submitMessage(MessageSubmitter.java:74)
	at org.holodeckb2b.backend.file.SubmitOperation.doProcessing(SubmitOperation.java:135)
	at org.holodeckb2b.common.workers.AbstractWorkerTask.run(AbstractWorkerTask.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

-----------------------------------------------------------------------------------------------------------------------------------------

**Log:**

2022-05-16 09:12:27,475 (pool-2-thread-4)[DEBUG] org.holodeckb2b.core.submission.MessageSubmitter - Start submission of new User Message
2022-05-16 09:12:27,475 (pool-2-thread-4)[TRACE] org.holodeckb2b.core.submission.MessageSubmitter - Get the P-Mode for the message
2022-05-16 09:12:27,475 (pool-2-thread-4)[DEBUG] org.holodeckb2b.core.submission.MessageSubmitter - Found P-Mode: ex-pm-pull-x509
2022-05-16 09:12:27,475 (pool-2-thread-4)[TRACE] org.holodeckb2b.core.submission.MessageSubmitter - Check for completeness: combined with P-Mode all info must be known
2022-05-16 09:12:27,491 (pool-2-thread-4)[ERROR] org.holodeckb2b.backend.file.SubmitOperation - An error occured when processing message meta data from ex-mmd-pull-x509.mmd. Details: null

**Comment by brianHK79** [comment]
Hello!

Exactly the same problem at me, with ex-pm-pull-ut-init.xml, ex-pm-pull-x509-init.xml.
 - Holodeck 5.3.2
 - Java 1.8.0.251
 - Windows 10 Pro 21H2

Any news about this issue?
Thank you for your help.

**Comment by brianHK79** [comment]
Hello @hkreetz,

I've found the answer in closed issue: https://github.com/holodeck-b2b/Holodeck-B2B/issues/126
It works for me fine!

Regards

**Comment by hkreetz** [comment]
Hi brianHK79,

thanks a lot! Works for me as well. 
But a Null Pointer Exception shouldn't happened at this point anyway. 

Regards
