### ISSUE TITLE
CLI and GUI interfaces binding to external addresses.

### ISSUE THREAD

**Issue by IsaacN72** [holodeck-b2b/Holodeck-B2B#153]
**which version of Holodeck B2B you are using**: holodeckb2b-6.1.0/
**your operating system:** Linux (Ubuntu 18.10)
**your Java version:** openjdk version "1.8.0_362"
**error messages you received:**
`_java.lang.Exception: Could not connect to Holodeck B2B on port 1701
	at org.holodeckb2b.ui.app.gui.HB2BMonitoringApp.main(HB2BMonitoringApp.java:112)
Caused by: java.rmi.ConnectException: Connection refused to host: **1.2.3.4**; nested exception is: 
	java.net.ConnectException: Connection timed out (Connection timed out)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
	at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
	at org.holodeckb2b.ui.app.gui.HB2BMonitoringApp.main(HB2BMonitoringApp.java:109)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)_

**what you were trying to do and what the problem was you encountered:** Attempting to run either cli or GUI monitoring interfaces
was the problem reproducible: Yes
**Additional information:** The RMI server is running on the default port 1701 (I can telnet to it) however the monitoring applications seem to be attempting to connect to external IP addresses rather than local host. Is there a way to either bind it to localhost, or direct the monitoring interfaces to localhost?

**Comment by sfieten** [comment]
I have looked into this but not able to reproduce this issue, so I cannot determine why this fails. But it looks like the RMI client does not use the localhost. Maybe specifying the host explicitly can help to resolve this. We will include this in a future release.
